### ISSUE TITLE
Create Inventory Interface

### ISSUE THREAD

**Issue by rupertraphael** [HN67/Jerra#4]
An Inventory should represent a collection of Items, potentially ordered. The core functionality of an Inventory needs to be able to allow adding Item's to the Inventory and track how many copies of each Item has been added. An Inventory does not need to expose how it internally stores Item's, only provide functionality to check the count of an Item. Items should be considered identical (and counted with the same count) if they are equal by their .equals(Item) method. An Inventory may also expose attributes such as the total number of Items it contains, the number of different Items it contains, etc.

**Comment by HN67** [comment]
Resolving this issue should now also include a concrete implementation of Inventory, probably HashInventory, which uses a HashMap internally.
